import { MdOutlineInput, MdPassword, MdSearch } from 'react-icons/md'
import { LiaHandPointerSolid } from 'react-icons/lia'
import { LuFormInput } from 'react-icons/lu'
import { GoNumber, GoSingleSelect } from 'react-icons/go'
import type { InputProps, ButtonProps, InputNumberProps, SelectProps } from 'antd'
import type { PasswordProps } from 'antd/es/input/Password'
import type { SearchProps } from 'antd/es/input/Search'
import type { TextAreaProps } from 'antd/es/input/TextArea'
import type { ComponentItem } from '../types'

export const componentList: ComponentItem[] = [
  {
    type: 'button',
    label: '按钮',
    field: 'button',
    icon: LiaHandPointerSolid,
    labelCol: 2,
    attrs: <ButtonProps>{
      block: false,
      danger: false,
      ghost: false,
      href: '',
      htmlType: 'button',
      icon: null,
      loading: false,
      shape: 'default',
      size: 'middle',
      target: '',
      type: 'default',
      value: '按钮',
    },
  },
  {
    type: 'input',
    label: '单行文本',
    icon: LuFormInput,
    labelCol: 2,
    field: 'inputValue',
    rules: [],
    required: true,
    value: '',
    attrs: <InputProps>{
      addonAfter: null,
      addonBefore: null,
      allowClear: false,
      bordered: true,
      placeholder: '请输入',
      disabled: false,
      maxLength: undefined,
      showCount: false,
      status: '',
      prefix: '',
      size: 'middle',
      suffix: '',
      readOnly: false,
    },
  },
  {
    type: 'password',
    label: '密码框',
    required: true,
    icon: MdPassword,
    labelCol: 2,
    field: 'inputValue',
    rules: [],
    value: '',
    attrs: <PasswordProps>{
      addonAfter: null,
      addonBefore: null,
      allowClear: false,
      bordered: true,
      placeholder: '请输入',
      disabled: false,
      maxLength: undefined,
      showCount: false,
      status: '',
      prefix: null,
      size: 'middle',
      suffix: null,
      visibilityToggle: true,
      readOnly: false,
    },
  },
  {
    type: 'search',
    label: '搜索框',
    icon: MdSearch,
    labelCol: 2,
    required: true,
    field: 'inputValue',
    rules: [],
    value: '',
    attrs: <SearchProps>{
      addonAfter: null,
      addonBefore: null,
      allowClear: false,
      bordered: true,
      placeholder: '请输入',
      disabled: false,
      maxLength: undefined,
      showCount: false,
      status: '',
      prefix: null,
      size: 'middle',
      suffix: null,
      enterButton: true,
      readOnly: false,
    },
  },
  {
    type: 'textarea',
    label: '文本域',
    required: true,
    icon: MdOutlineInput,
    labelCol: 2,
    field: 'inputValue',
    value: '',
    rules: [],
    attrs: <TextAreaProps>{
      addonAfter: null,
      autoSize: false,
      bordered: true,
      maxLength: undefined,
      showCount: false,
      readOnly: false,
    },
  },
  {
    type: 'inputNumber',
    label: '计数器',
    icon: GoNumber,
    labelCol: 2,
    field: 'inputNumberValue',
    rules: [],
    required: true,
    value: '',
    attrs: <InputNumberProps>{
      addonAfter: null,
      addonBefore: null,
      bordered: true,
      placeholder: '请输入',
      disabled: false,
      status: '',
      prefix: '',
      size: 'middle',
      suffix: '',
      readOnly: false,
      max: undefined,
      min: undefined,
      step: 1,
      stringMode: false,
      controls: true,
      decimalSeparator: '',
      keyboard: true,
      precision: undefined,
    },
  },
  {
    type: 'select',
    label: '下拉选择',
    icon: GoSingleSelect,
    labelCol: 2,
    field: 'selectValue',
    rules: [],
    required: true,
    value: undefined,
    children: [
      {
        type: 'option',
        attrs: {
          value: '1',
          label: '选项1',
        },
      },
      {
        type: 'option',
        attrs: {
          value: '2',
          label: '选项2',
        },
      },
    ],
    attrs: <SelectProps>{
      allowClear: false,
      autoFocus: false,
      bordered: true,
      defaultActiveFirstOption: true,
      disabled: false,
      filterOption: false,
      loading: false,
      maxTagCount: undefined,
      mode: undefined,
      placeholder: '请选择',
      placement: 'bottomLeft',
      showSearch: false,
      size: 'middle',
      status: '',
      virtual: true,
    },
  },
]
